#!/bin/bash

# 自动初始化云开发数据库脚本

PROJECT_PATH="/Users/xu/Documents/SRC_wechat"
APPID="wxfab0c5bd74364f44"
ENV_ID="cloud1-2gyhe7s5efa4155f"

echo "========================================"
echo "  云开发数据库初始化工具"
echo "========================================"
echo ""
echo "📱 小程序信息:"
echo "   项目路径：$PROJECT_PATH"
echo "   AppID: $APPID"
echo "   云开发环境：$ENV_ID"
echo ""
echo "========================================"
echo "  请按以下步骤操作:"
echo "========================================"
echo ""
echo "1. 微信开发者工具应该已经打开项目"
echo "   如果没有打开，正在启动..."
/Applications/wechatwebdevtools.app/Contents/MacOS/cli open --project $PROJECT_PATH &

echo ""
echo "2. 在微信开发者工具中:"
echo "   a) 点击菜单「工具」→「清除缓存」→「清除全部数据」"
echo "   b) 点击工具栏「编译」按钮"
echo "   c) 小程序会自动打开初始化页面并创建数据库集合"
echo ""
echo "3. 等待 3 秒后会自动跳转到首页"
echo ""
echo "========================================"
echo "  如果自动初始化失败，请手动操作:"
echo "========================================"
echo ""
echo "1. 点击工具栏「云开发」按钮"
echo "2. 点击左侧「云函数」菜单"
echo "3. 找到 'init' 云函数"
echo "4. 右键点击选择「运行」"
echo ""
echo "========================================"
echo ""
echo "💡 提示：初始化完成后，点击「立即登录」按钮测试登录功能"
echo ""
